# Generated by Django 4.1 on 2022-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detatil', models.TextField(default=None)),
            ],
            options={
                'db_table': 'Product_detail',
            },
        ),
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('ali_price', models.IntegerField(default=None)),
                ('ot_price', models.IntegerField(default=None)),
                ('image', models.TextField(default='https://user-images.githubusercontent.com/67406924/188814013-dcb28a56-615c-4a9f-ba2d-e0ab41593134.png')),
            ],
            options={
                'db_table': 'Product_list',
            },
        ),
    ]
