# Generated by Django 4.1 on 2022-09-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ali_price', models.IntegerField()),
                ('ot_price', models.IntegerField()),
            ],
        ),
    ]
