# Generated by Django 4.1 on 2022-09-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_list_image_alter_product_list_ali_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='image',
            field=models.ImageField(default='..static/product/iages/test.jpg', upload_to=''),
        ),
    ]
