# Generated by Django 4.1 on 2022-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_list_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ali_price', models.IntegerField(default=None)),
                ('ot_price', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'Product_detail',
            },
        ),
        migrations.AlterField(
            model_name='product_list',
            name='image',
            field=models.ImageField(default='../static/product/images/test.jpg', upload_to=''),
        ),
    ]
